### ISSUE TITLE
A spelling error and a confusing error raised

### ISSUE THREAD

**Issue by yiheng-wu** [WalterDehnen/patternSpeed#1]
There is a spelling error in line 774, “minNbin=Default.minNBin” should be “minNBin=Default.minNBin” 

And a confusing error raised:
In line 649, "i0=0,i1=0" is returned by function findBarRegion, and it will raise error in line 294, since i1<=i0. It must be some logical problem here.

**Comment by WalterDehnen** [comment]
Fixed the spelling error.

The other one is not an error: findBarRegion returns i0,i1=0,0 if no bar can be identified. 
I added improved warning/error messages and avoid running into them in the combined method FourierMethod.patternSpeed().
